// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjorcfywnnbajnpkgmqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqb3JjZnl3bm5iYWpucGtnbXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTAzNjIsImV4cCI6MjA3MTk4NjM2Mn0.Bs-cLM40_nw5ovg8oUU1OcJNoR11y6x64NxtdEqE72U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});